version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    volumes:
       - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleuron
      MYSQL_USER: root

  nginx:
    image: nginx:latest
    ports:
      - 8500:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paie
      - approvisionnement
      - production

  paie:
    build: Paie/
    depends_on:
      - mariadb

  production:
    build: Production/
    depends_on:
      - mariadb

  # production2:
  #   build: Production/
  #   depends_on:
  #     - mariadb
  #   environment:
  #     PORT: 8510
  #     PATH: /production/sites/2/projets

  approvisionnement:
    build: ApprovisionnmentTestDocker/
    depends_on:
      - mariadb

volumes:
  data: