version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    volumes:
       - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleuron
      MYSQL_USER: root

  nginx:
    image: nginx:latest
    ports:
      - 8500:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paie
      - production1
      - production2
      - approvisionnement

  paie:
    build: paie/
    depends_on:
      - mariadb

  production1:
    build: production/
    depends_on:
      - mariadb
    environment:
      PORT: 8510
      PATH: /production1/


  production2:
    build: production/
    depends_on:
      - mariadb
    environment:
      PORT: 8511
      PATH: /production2/

  approvisionnement:
    build: ApprovisionnmentTestDocker/
    depends_on:
      - mariadb

volumes:
  data: