version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    volumes:
       - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleuron
      MYSQL_USER: root

  nginx:
    image: nginx:latest
    ports:
      - 8500:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paie
      - production1
      - production2
      - approvisionnement

  paie:
    build: Paie/
    depends_on:
      - mariadb

  Production:
    build: Production/
    depends_on:
      - mariadb

  apprivisionnement:
    build: ApprovisionnementTestDocker/
    depends_on:
      - mariadb

volumes:
  data: