version: "3.8"

services:

  mariadb:
    image: mariadb:latest
    volumes:
       - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: domestique
      MYSQL_USER: root

  nginx:
    image: nginx:latest
    ports:
      - 8500:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - paie
      - production1
      - production2

  paie:
    build: Budget/
    depends_on:
      - mariadb

  tache:
    build: taches_python/
    depends_on:
      - mariadb

volumes:
  data: